[package]
name = "maze"
version = "0.1.0"
authors = [ "Boris Faure <billiob@gmail.com>" ]
license = "BSD-2-Clause"
edition = '2021'

[dependencies]
docopt = "1.1"
rand = { version = "0.9", features = ["std", "std_rng"] }
color_scaling = "0.1"
image = "0.25"
gif = "0.14"
read_color = "1"
